-- Contact Submissions Table
CREATE TABLE IF NOT EXISTS contact_submissions (
  id TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  message TEXT NOT NULL,
  services JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Tool Notifications Table (For upcoming tools)
CREATE TABLE IF NOT EXISTS tool_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tool_id TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tool_id, email)
);

-- Basic RLS Policies (Enable for security in production)
-- ALTER TABLE contact_submissions ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public insert" ON contact_submissions FOR INSERT WITH CHECK (true);

-- ALTER TABLE tool_notifications ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow public insert" ON tool_notifications FOR INSERT WITH CHECK (true);
